In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_excel("../data/cleaned_dataset.xlsx")

In [5]:
df.head()

,Age_Range,Gender,Education_Level,Employment_Status,Marital_Status,EatLess_OnWeightGain,EatLess_AtMealtime,RefuseFood_WeightConcern,Monitor_Food,Eat_SlimmingFoods,...,Days_TriedLimitFoodControlShapeOrWeight,Days_FastedControlShapeOrWeight,Days_ExcludedFoodControlShapeOrWeight,Days_FollowedRulesControlShapeOrWeight,Days_FearLosingControlOverEating,Eat_SpecificFoodsHabitually,Location_TriggersHabitualEating,AutomaticEating_WhenExperiencingStrongEmotion,Realize_AfterEatingOutOfHabit,Perception_EatingDisorder
0,18-24,Female,Bachelor's degree,Employed part-time,Married,3,3,3,3,3,...,Every day,Every day,Every day,Every day,Every day,2,0,0,2,Probably yes
1,18-24,Female,Bachelor's degree,Student,Single,3,2,2,3,2,...,Every day,13-15 days,13-15 days,Every day,6-12 days,2,1,2,2,Probably yes
2,18-24,Female,College,Student,Single,0,0,0,0,0,...,No days,No days,No days,No days,No days,0,0,0,0,"No, I don’t believe I do"
3,18-24,Female,College,Student,Single,2,2,1,3,2,...,No days,No days,No days,No days,1-5 days,2,2,1,3,Probably not
4,18-24,Female,College,Student,Single,0,0,0,3,2,...,No days,No days,No days,No days,No days,2,0,1,2,"No, I don’t believe I do"

In [4]:
df.shape

(550, 56)

In [5]:
df.columns.tolist()

['Age_Range',
 'Gender',
 'Education_Level',
 'Employment_Status',
 'Marital_Status',
 'EatLess_OnWeightGain',
 'EatLess_AtMealtime',
 'RefuseFood_WeightConcern',
 'Monitor_Food',
 'Eat_SlimmingFoods',
 'EatLess_AfterOvereating',
 'EatLess_ToPreventWeightGain',
 'AvoidSnacks_BetweenMealsToWatchWeight',
 'AvoidEveningEating_ToWatchWeight',
 'ConsiderWeight_WhenEating',
 'Eat_WhenIrritated',
 'Eat_WhenUnoccupied',
 'Eat_WhenDepressedOrDiscouraged',
 'Eat_WhenLonely',
 'Eat_WhenSomeoneLetDown',
 'Eat_WhenAngry',
 'Eat_WhenExpectingBad',
 'Eat_WhenAnxious',
 'Eat_WhenThingsGoWrong',
 'Eat_WhenFrightened',
 'Eat_WhenDisappointed',
 'Eat_WhenEmotionallyUpset',
 'Eat_WhenBoredOrRestless',
 'EatMore_IfFoodTasty',
 'EatMore_IfFoodSmellsOrLooksGood',
 'Eat_WhenSeeDeliciousFood',
 'Eat_DeliciousFoodImmediately',
 'DesireToBuy_FromBakery',
 'DesireToBuy _FromSnackBarOrCafe',
 'DesireToEat_WhenSeeOthersEating',
 'Resist_DeliciousFood',
 'EatMore_WhenSeeOthersEating',
 'Eat_WhenPreparingMeal',
 'Days_DesireForFlatStomach',
 'Days_FeltFat',
 'Days_WeightAffectedSelfJudgment',
 'Days_ShapeAffectedSelfJudgment',
 'Days_DissatisfiedWithWeight',
 'Days_DissatisfiedWithShape',
 'Days_UncomfortableToSeeOwnBody',
 'Days_UncomfortableBecauseOthersSeeingShape',
 'Days_TriedLimitFoodControlShapeOrWeight',
 'Days_FastedControlShapeOrWeight',
 'Days_ExcludedFoodControlShapeOrWeight',
 'Days_FollowedRulesControlShapeOrWeight',
 'Days_FearLosingControlOverEating',
 'Eat_SpecificFoodsHabitually',
 'Location_TriggersHabitualEating',
 'AutomaticEating_WhenExperiencingStrongEmotion',
 'Realize_AfterEatingOutOfHabit',
 'Perception_EatingDisorder']

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 56 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age_Range                                      550 non-null    object
 1   Gender                                         550 non-null    object
 2   Education_Level                                550 non-null    object
 3   Employment_Status                              550 non-null    object
 4   Marital_Status                                 550 non-null    object
 5   EatLess_OnWeightGain                           550 non-null    int64
 6   EatLess_AtMealtime                             550 non-null    int64
 7   RefuseFood_WeightConcern                       550 non-null    int64
 8   Monitor_Food                                   550 non-null    int64
 9   Eat_SlimmingFoods                              550 non-null    int64
 10  EatLess_AfterOvereating                        550 non-null    int64
 11  EatLess_ToPreventWeightGain                    550 non-null    int64
 12  AvoidSnacks_BetweenMealsToWatchWeight          550 non-null    int64
 13  AvoidEveningEating_ToWatchWeight               550 non-null    int64
 14  ConsiderWeight_WhenEating                      550 non-null    int64
 15  Eat_WhenIrritated                              550 non-null    int64
 16  Eat_WhenUnoccupied                             550 non-null    int64
 17  Eat_WhenDepressedOrDiscouraged                 550 non-null    int64
 18  Eat_WhenLonely                                 550 non-null    int64
 19  Eat_WhenSomeoneLetDown                         550 non-null    int64
 20  Eat_WhenAngry                                  550 non-null    int64
 21  Eat_WhenExpectingBad                           550 non-null    int64
 22  Eat_WhenAnxious                                550 non-null    int64
 23  Eat_WhenThingsGoWrong                          550 non-null    int64
 24  Eat_WhenFrightened                             550 non-null    int64
 25  Eat_WhenDisappointed                           550 non-null    int64
 26  Eat_WhenEmotionallyUpset                       550 non-null    int64
 27  Eat_WhenBoredOrRestless                        550 non-null    int64
 28  EatMore_IfFoodTasty                            550 non-null    int64
 29  EatMore_IfFoodSmellsOrLooksGood                550 non-null    int64
 30  Eat_WhenSeeDeliciousFood                       550 non-null    int64
 31  Eat_DeliciousFoodImmediately                   550 non-null    int64
 32  DesireToBuy_FromBakery                         550 non-null    int64
 33  DesireToBuy _FromSnackBarOrCafe                550 non-null    int64
 34  DesireToEat_WhenSeeOthersEating                550 non-null    int64
 35  Resist_DeliciousFood                           550 non-null    int64
 36  EatMore_WhenSeeOthersEating                    550 non-null    int64
 37  Eat_WhenPreparingMeal                          550 non-null    int64
 38  Days_DesireForFlatStomach                      550 non-null    object
 39  Days_FeltFat                                   550 non-null    object
 40  Days_WeightAffectedSelfJudgment                550 non-null    object
 41  Days_ShapeAffectedSelfJudgment                 550 non-null    object
 42  Days_DissatisfiedWithWeight                    550 non-null    object
 43  Days_DissatisfiedWithShape                     550 non-null    object
 44  Days_UncomfortableToSeeOwnBody                 550 non-null    object
 45  Days_UncomfortableBecauseOthersSeeingShape     550 non-null    object
 46  Days_TriedLimitFoodControlShapeOrWeight        550 non-null    object
 47  Days_FastedControlShapeOrWeight                550 non-null    object
 48  Days_ExcludedFoodControlShapeOrWeight          550 non-null    object
 49  Days_FollowedRulesControlShapeOrWeight         550 non-null    object
 50  Days_FearLosingControlOverEating               550 non-null    object
 51  Eat_SpecificFoodsHabitually                    550 non-null    int64
 52  Location_TriggersHabitualEating                550 non-null    int64
 53  AutomaticEating_WhenExperiencingStrongEmotion  550 non-null    int64
 54  Realize_AfterEatingOutOfHabit                  550 non-null    int64
 55  Perception_EatingDisorder                      550 non-null    object
dtypes: int64(37), object(19)
memory usage: 240.8+ KB

In [7]:
df.isnull().sum()

Age_Range                                        0
Gender                                           0
Education_Level                                  0
Employment_Status                                0
Marital_Status                                   0
EatLess_OnWeightGain                             0
EatLess_AtMealtime                               0
RefuseFood_WeightConcern                         0
Monitor_Food                                     0
Eat_SlimmingFoods                                0
EatLess_AfterOvereating                          0
EatLess_ToPreventWeightGain                      0
AvoidSnacks_BetweenMealsToWatchWeight            0
AvoidEveningEating_ToWatchWeight                 0
ConsiderWeight_WhenEating                        0
Eat_WhenIrritated                                0
Eat_WhenUnoccupied                               0
Eat_WhenDepressedOrDiscouraged                   0
Eat_WhenLonely                                   0
Eat_WhenSomeoneLetDown                           0
Eat_WhenAngry                                    0
Eat_WhenExpectingBad                             0
Eat_WhenAnxious                                  0
Eat_WhenThingsGoWrong                            0
Eat_WhenFrightened                               0
Eat_WhenDisappointed                             0
Eat_WhenEmotionallyUpset                         0
Eat_WhenBoredOrRestless                          0
EatMore_IfFoodTasty                              0
EatMore_IfFoodSmellsOrLooksGood                  0
Eat_WhenSeeDeliciousFood                         0
Eat_DeliciousFoodImmediately                     0
DesireToBuy_FromBakery                           0
DesireToBuy _FromSnackBarOrCafe                  0
DesireToEat_WhenSeeOthersEating                  0
Resist_DeliciousFood                             0
EatMore_WhenSeeOthersEating                      0
Eat_WhenPreparingMeal                            0
Days_DesireForFlatStomach                        0
Days_FeltFat                                     0
Days_WeightAffectedSelfJudgment                  0
Days_ShapeAffectedSelfJudgment                   0
Days_DissatisfiedWithWeight                      0
Days_DissatisfiedWithShape                       0
Days_UncomfortableToSeeOwnBody                   0
Days_UncomfortableBecauseOthersSeeingShape       0
Days_TriedLimitFoodControlShapeOrWeight          0
Days_FastedControlShapeOrWeight                  0
Days_ExcludedFoodControlShapeOrWeight            0
Days_FollowedRulesControlShapeOrWeight           0
Days_FearLosingControlOverEating                 0
Eat_SpecificFoodsHabitually                      0
Location_TriggersHabitualEating                  0
AutomaticEating_WhenExperiencingStrongEmotion    0
Realize_AfterEatingOutOfHabit                    0
Perception_EatingDisorder                        0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.describe()

,EatLess_OnWeightGain,EatLess_AtMealtime,RefuseFood_WeightConcern,Monitor_Food,Eat_SlimmingFoods,EatLess_AfterOvereating,EatLess_ToPreventWeightGain,AvoidSnacks_BetweenMealsToWatchWeight,AvoidEveningEating_ToWatchWeight,ConsiderWeight_WhenEating,...,DesireToBuy_FromBakery,DesireToBuy _FromSnackBarOrCafe,DesireToEat_WhenSeeOthersEating,Resist_DeliciousFood,EatMore_WhenSeeOthersEating,Eat_WhenPreparingMeal,Eat_SpecificFoodsHabitually,Location_TriggersHabitualEating,AutomaticEating_WhenExperiencingStrongEmotion,Realize_AfterEatingOutOfHabit
count,550.000000,550.000000,550.000000,550.000000,550.000000,550.000000,550.000000,550.000000,550.000000,550.000000,...,550.000000,550.000000,550.000000,550.000000,550.000000,550.000000,550.000000,550.000000,550.000000,550.000000
mean,1.523636,1.507273,1.316364,2.172727,1.365455,1.481818,1.443636,1.398182,1.383636,1.418182,...,1.925455,1.925455,1.507273,1.645455,1.187273,1.807273,1.600000,1.454545,1.400000,1.734545
std,1.144554,1.203721,1.234708,1.253477,1.261410,1.295444,1.273059,1.271660,1.319638,1.284501,...,1.173434,1.168768,1.220253,1.245658,1.247008,1.190101,1.281791,1.279204,1.280369,1.249585
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
50%,2.000000,2.000000,1.000000,2.000000,1.000000,2.000000,1.500000,1.000000,1.000000,1.000000,...,2.000000,2.000000,1.000000,2.000000,1.000000,2.000000,2.000000,2.000000,1.000000,2.000000
75%,2.000000,2.000000,2.000000,3.000000,2.000000,2.750000,2.000000,2.000000,2.000000,2.000000,...,3.000000,3.000000,2.000000,3.000000,2.000000,3.000000,2.000000,2.000000,2.000000,3.000000
max,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,...,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000

In [10]:
object_cols = df.select_dtypes(include=["object"]).columns.tolist()
object_cols

['Age_Range',
 'Gender',
 'Education_Level',
 'Employment_Status',
 'Marital_Status',
 'Days_DesireForFlatStomach',
 'Days_FeltFat',
 'Days_WeightAffectedSelfJudgment',
 'Days_ShapeAffectedSelfJudgment',
 'Days_DissatisfiedWithWeight',
 'Days_DissatisfiedWithShape',
 'Days_UncomfortableToSeeOwnBody',
 'Days_UncomfortableBecauseOthersSeeingShape',
 'Days_TriedLimitFoodControlShapeOrWeight',
 'Days_FastedControlShapeOrWeight',
 'Days_ExcludedFoodControlShapeOrWeight',
 'Days_FollowedRulesControlShapeOrWeight',
 'Days_FearLosingControlOverEating',
 'Perception_EatingDisorder']

In [11]:
object_cols = df.select_dtypes(include=["object"]).columns.tolist()
print(object_cols)

['Age_Range', 'Gender', 'Education_Level', 'Employment_Status', 'Marital_Status', 'Days_DesireForFlatStomach', 'Days_FeltFat', 'Days_WeightAffectedSelfJudgment', 'Days_ShapeAffectedSelfJudgment', 'Days_DissatisfiedWithWeight', 'Days_DissatisfiedWithShape', 'Days_UncomfortableToSeeOwnBody', 'Days_UncomfortableBecauseOthersSeeingShape', 'Days_TriedLimitFoodControlShapeOrWeight', 'Days_FastedControlShapeOrWeight', 'Days_ExcludedFoodControlShapeOrWeight', 'Days_FollowedRulesControlShapeOrWeight', 'Days_FearLosingControlOverEating', 'Perception_EatingDisorder']

In [12]:
df_encoded = pd.get_dummies(df, drop_first=True)
df_encoded.head()

,EatLess_OnWeightGain,EatLess_AtMealtime,RefuseFood_WeightConcern,Monitor_Food,Eat_SlimmingFoods,EatLess_AfterOvereating,EatLess_ToPreventWeightGain,AvoidSnacks_BetweenMealsToWatchWeight,AvoidEveningEating_ToWatchWeight,ConsiderWeight_WhenEating,...,Days_FollowedRulesControlShapeOrWeight_Every day,Days_FollowedRulesControlShapeOrWeight_No days,Days_FearLosingControlOverEating_13-15 days,Days_FearLosingControlOverEating_6-12 days,Days_FearLosingControlOverEating_Every day,Days_FearLosingControlOverEating_No days,"Perception_EatingDisorder_Possibly, but I am not sure",Perception_EatingDisorder_Probably not,Perception_EatingDisorder_Probably yes,"Perception_EatingDisorder_Yes, I believe I do"
0,3,3,3,3,3,3,3,3,3,2,...,True,False,False,False,True,False,False,False,True,False
1,3,2,2,3,2,4,3,4,3,2,...,True,False,False,True,False,False,False,False,True,False
2,0,0,0,0,0,0,0,0,0,0,...,False,True,False,False,False,True,False,False,False,False
3,2,2,1,3,2,1,3,1,0,2,...,False,True,False,False,False,False,False,True,False,False
4,0,0,0,3,2,0,0,0,2,2,...,False,True,False,False,False,True,False,False,False,False

In [13]:
df_encoded.columns.tolist()

['EatLess_OnWeightGain',
 'EatLess_AtMealtime',
 'RefuseFood_WeightConcern',
 'Monitor_Food',
 'Eat_SlimmingFoods',
 'EatLess_AfterOvereating',
 'EatLess_ToPreventWeightGain',
 'AvoidSnacks_BetweenMealsToWatchWeight',
 'AvoidEveningEating_ToWatchWeight',
 'ConsiderWeight_WhenEating',
 'Eat_WhenIrritated',
 'Eat_WhenUnoccupied',
 'Eat_WhenDepressedOrDiscouraged',
 'Eat_WhenLonely',
 'Eat_WhenSomeoneLetDown',
 'Eat_WhenAngry',
 'Eat_WhenExpectingBad',
 'Eat_WhenAnxious',
 'Eat_WhenThingsGoWrong',
 'Eat_WhenFrightened',
 'Eat_WhenDisappointed',
 'Eat_WhenEmotionallyUpset',
 'Eat_WhenBoredOrRestless',
 'EatMore_IfFoodTasty',
 'EatMore_IfFoodSmellsOrLooksGood',
 'Eat_WhenSeeDeliciousFood',
 'Eat_DeliciousFoodImmediately',
 'DesireToBuy_FromBakery',
 'DesireToBuy _FromSnackBarOrCafe',
 'DesireToEat_WhenSeeOthersEating',
 'Resist_DeliciousFood',
 'EatMore_WhenSeeOthersEating',
 'Eat_WhenPreparingMeal',
 'Eat_SpecificFoodsHabitually',
 'Location_TriggersHabitualEating',
 'AutomaticEating_WhenExperiencingStrongEmotion',
 'Realize_AfterEatingOutOfHabit',
 'Age_Range_25-34',
 'Age_Range_35-44',
 'Age_Range_45 and above',
 'Age_Range_Under 18',
 'Gender_Male',
 'Education_Level_College',
 'Education_Level_High school or below',
 "Education_Level_Master's degree",
 'Education_Level_PhD or higher',
 'Employment_Status_Employed part-time',
 'Employment_Status_Self-employed',
 'Employment_Status_Student',
 'Employment_Status_Unemployed',
 'Marital_Status_Married',
 'Marital_Status_Single',
 'Days_DesireForFlatStomach_13-15 days',
 'Days_DesireForFlatStomach_6-12 days',
 'Days_DesireForFlatStomach_Every day',
 'Days_DesireForFlatStomach_No days',
 'Days_FeltFat_13-15 days',
 'Days_FeltFat_6-12 days',
 'Days_FeltFat_Every day',
 'Days_FeltFat_No days',
 'Days_WeightAffectedSelfJudgment_13-15 days',
 'Days_WeightAffectedSelfJudgment_6-12 days',
 'Days_WeightAffectedSelfJudgment_Every day',
 'Days_WeightAffectedSelfJudgment_No days',
 'Days_ShapeAffectedSelfJudgment_13-15 days',
 'Days_ShapeAffectedSelfJudgment_6-12 days',
 'Days_ShapeAffectedSelfJudgment_Every day',
 'Days_ShapeAffectedSelfJudgment_No days',
 'Days_DissatisfiedWithWeight_13-15 days',
 'Days_DissatisfiedWithWeight_6-12 days',
 'Days_DissatisfiedWithWeight_Every day',
 'Days_DissatisfiedWithWeight_No days',
 'Days_DissatisfiedWithShape_13-15 days',
 'Days_DissatisfiedWithShape_6-12 days',
 'Days_DissatisfiedWithShape_Every day',
 'Days_DissatisfiedWithShape_No days',
 'Days_UncomfortableToSeeOwnBody_13-15 days',
 'Days_UncomfortableToSeeOwnBody_6-12 days',
 'Days_UncomfortableToSeeOwnBody_Every day',
 'Days_UncomfortableToSeeOwnBody_No days',
 'Days_UncomfortableBecauseOthersSeeingShape_13-15 days',
 'Days_UncomfortableBecauseOthersSeeingShape_6-12 days',
 'Days_UncomfortableBecauseOthersSeeingShape_Every day',
 'Days_UncomfortableBecauseOthersSeeingShape_No days',
 'Days_TriedLimitFoodControlShapeOrWeight_13-15 days',
 'Days_TriedLimitFoodControlShapeOrWeight_6-12 days',
 'Days_TriedLimitFoodControlShapeOrWeight_Every day',
 'Days_TriedLimitFoodControlShapeOrWeight_No days',
 'Days_FastedControlShapeOrWeight_13-15 days',
 'Days_FastedControlShapeOrWeight_6-12 days',
 'Days_FastedControlShapeOrWeight_Every day',
 'Days_FastedControlShapeOrWeight_No days',
 'Days_ExcludedFoodControlShapeOrWeight_13-15 days',
 'Days_ExcludedFoodControlShapeOrWeight_6-12 days',
 'Days_ExcludedFoodControlShapeOrWeight_Every day',
 'Days_ExcludedFoodControlShapeOrWeight_No days',
 'Days_FollowedRulesControlShapeOrWeight_13-15 days',
 'Days_FollowedRulesControlShapeOrWeight_6-12 days',
 'Days_FollowedRulesControlShapeOrWeight_Every day',
 'Days_FollowedRulesControlShapeOrWeight_No days',
 'Days_FearLosingControlOverEating_13-15 days',
 'Days_FearLosingControlOverEating_6-12 days',
 'Days_FearLosingControlOverEating_Every day',
 'Days_FearLosingControlOverEating_No days',
 'Perception_EatingDisorder_Possibly, but I am not sure',
 'Perception_EatingDisorder_Probably not',
 'Perception_EatingDisorder_Probably yes',
 'Perception_EatingDisorder_Yes, I believe I do']

In [14]:
df_encoded.columns

Index(['EatLess_OnWeightGain', 'EatLess_AtMealtime',
       'RefuseFood_WeightConcern', 'Monitor_Food', 'Eat_SlimmingFoods',
       'EatLess_AfterOvereating', 'EatLess_ToPreventWeightGain',
       'AvoidSnacks_BetweenMealsToWatchWeight',
       'AvoidEveningEating_ToWatchWeight', 'ConsiderWeight_WhenEating',
       ...
       'Days_FollowedRulesControlShapeOrWeight_Every day',
       'Days_FollowedRulesControlShapeOrWeight_No days',
       'Days_FearLosingControlOverEating_13-15 days',
       'Days_FearLosingControlOverEating_6-12 days',
       'Days_FearLosingControlOverEating_Every day',
       'Days_FearLosingControlOverEating_No days',
       'Perception_EatingDisorder_Possibly, but I am not sure',
       'Perception_EatingDisorder_Probably not',
       'Perception_EatingDisorder_Probably yes',
       'Perception_EatingDisorder_Yes, I believe I do'],
      dtype='object', length=108)

In [15]:
import numpy as np

target_cols = [
    'Perception_EatingDisorder_Possibly, but I am not sure',
    'Perception_EatingDisorder_Probably not',
    'Perception_EatingDisorder_Probably yes',
    'Perception_EatingDisorder_Yes, I believe I do'
]

df_encoded["target"] = df_encoded[target_cols].idxmax(axis=1)

In [16]:
df_encoded["target"] = df_encoded["target"].str.replace("Perception_EatingDisorder_", "")

In [17]:
df_encoded = df_encoded.drop(columns=target_cols)

In [18]:
print("Shape:", df_encoded.shape)
print("\nFirst rows:")
display(df_encoded.head())

Shape: (550, 105)

First rows:

,EatLess_OnWeightGain,EatLess_AtMealtime,RefuseFood_WeightConcern,Monitor_Food,Eat_SlimmingFoods,EatLess_AfterOvereating,EatLess_ToPreventWeightGain,AvoidSnacks_BetweenMealsToWatchWeight,AvoidEveningEating_ToWatchWeight,ConsiderWeight_WhenEating,...,Days_ExcludedFoodControlShapeOrWeight_No days,Days_FollowedRulesControlShapeOrWeight_13-15 days,Days_FollowedRulesControlShapeOrWeight_6-12 days,Days_FollowedRulesControlShapeOrWeight_Every day,Days_FollowedRulesControlShapeOrWeight_No days,Days_FearLosingControlOverEating_13-15 days,Days_FearLosingControlOverEating_6-12 days,Days_FearLosingControlOverEating_Every day,Days_FearLosingControlOverEating_No days,target
0,3,3,3,3,3,3,3,3,3,2,...,False,False,False,True,False,False,False,True,False,Probably yes
1,3,2,2,3,2,4,3,4,3,2,...,False,False,False,True,False,False,True,False,False,Probably yes
2,0,0,0,0,0,0,0,0,0,0,...,True,False,False,False,True,False,False,False,True,"Possibly, but I am not sure"
3,2,2,1,3,2,1,3,1,0,2,...,True,False,False,False,True,False,False,False,False,Probably not
4,0,0,0,3,2,0,0,0,2,2,...,True,False,False,False,True,False,False,False,True,"Possibly, but I am not sure"

In [19]:
df_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Columns: 105 entries, EatLess_OnWeightGain to target
dtypes: bool(67), int64(37), object(1)
memory usage: 199.4+ KB

In [20]:
print("==== FINAL DATA CHECK ====")

print("\nShape:", df_encoded.shape)

print("\nMissing values:", df_encoded.isnull().sum().sum())

print("\nDuplicates:", df_encoded.duplicated().sum())

print("\nObject columns:", df_encoded.select_dtypes(include=["object"]).columns.tolist())

print("\nTarget distribution:")
print(df_encoded["target"].value_counts())

==== FINAL DATA CHECK ====

Shape: (550, 105)

Missing values: 0

Duplicates: 0

Object columns: ['target']

Target distribution:
target
Possibly, but I am not sure    246
Probably not                   120
Probably yes                   113
Yes, I believe I do             71
Name: count, dtype: int64

In [22]:
df_encoded.to_excel("../data/final_cleaned_dataset.xlsx", index=False)